/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

const fileMap = {
  
  "arbitration.baml": "class ArbitrationSynthesis {\n  synthesis string\n  rationale string\n  top_roles string[]\n}\n",
  "clients.baml": "client<llm> NimDefault {\n  provider \"openai-generic\"\n  options {\n    base_url env.NIM_BASE_URL\n    api_key env.NVIDIA_API_KEY\n    model \"deepseek-ai/deepseek-v4-flash\"\n  }\n}\n",
  "generators.baml": "generator typescript {\n  output_type \"typescript\"\n  output_dir \"../src\"\n  module_format \"esm\"\n  version \"0.222.0\"\n}\n",
  "hippocampus.baml": "class HippocampusWrite {\n  layer \"shared\" | \"context\"\n  category string\n  content string\n  tags string\n  confidence float\n  expires_at int?\n  supersedes string[]?\n}\n\nclass TaskAdd {\n  title string\n  description string?\n  priority \"low\" | \"normal\" | \"high\"\n  due_at int?\n  tags string?\n}\n",
}
export const getBamlFiles = () => {
    return fileMap;
}