/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types.js"
import type {  ArbitrationSynthesis,  HippocampusWrite,  TaskAdd } from "./types.js"
import type * as types from "./types.js"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface ArbitrationSynthesis {
      synthesis?: string | null
      rationale?: string | null
      top_roles: string[]
    }
    export interface HippocampusWrite {
      layer?: "shared" | "context" | null
      category?: string | null
      content?: string | null
      tags?: string | null
      confidence?: number | null
      expires_at?: number | null
      supersedes?: string[] | null
    }
    export interface TaskAdd {
      title?: string | null
      description?: string | null
      priority?: "low" | "normal" | "high" | null
      due_at?: number | null
      tags?: string | null
    }
}